### ISSUE TITLE
Accessing current sorable list

### ISSUE THREAD

**Issue by Ceany** [mharris717/ember-drag-drop#117]
I have a short question regarding how to access the data.

I have 5 different rows where data is separated. I want to drag and drop items between each row. But when I drop an item I want to update it to persist the selected row.

How can I access the `sortableObjectList` object for the row where I dropped in my item?

When I add the list to the `sortEndAction` callback in the addon code it is working. But hopefully there is a better way to do this.

Thanks in advance.
Maxi

**Comment by dgavey** [comment]
Not 100% sure what you're asking for, but considering that you pass in the objects to `sortableObjectList` you have access to them. If you need to know specific things about what item is being moved then there is the `dragStartAction` as part of the draggable-object.

**Comment by dgavey** [comment]
For multiple lists, I think the [ember-drag-sort](https://github.com/Deveo/ember-drag-sort) might be a more appropriate addon

**Comment by Ceany** [comment]
thanks a lot. your tip with dragStartAction completely solved my problem with empty list
