### ISSUE TITLE
Upgrade ember-cli-babel 5.x -> 6.x to eliminate deprecation warning

### ISSUE THREAD

**Issue by jacobq** [mharris717/ember-drag-drop#121]
The current release (0.4.7) triggers an annoying deprecation warning with recent versions of Ember, which would be fixed by upgrading to the latest releases of `ember-cli-babel` (6.11.x). Please consider upgrading this [here](https://github.com/mharris717/ember-drag-drop/blob/5fe6a17cc378a07af1497373db9ea24d89ccc125/package.json#L49).

```
├─┬ ember-drag-drop@0.4.7
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
```

The deprecation warning looks like this and is described [here](https://github.com/ember-cli/ember-cli-version-checker/issues/48):
```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/path/to/project/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

**Comment by nlfurniss** [comment]
Fix is in #124
