### ISSUE TITLE
[Warning] DEPRECATION: Accessing jQuery.Event specific properties is deprecated

### ISSUE THREAD

**Issue by andrewhavens** [mharris717/ember-drag-drop#134]
Getting started working with this add-on. Noticed a LOT of these warnings in the console. Not sure if this is an assumed setup step, or a recent deprecation, but I thought it would be good to mention it. I'm not sure which is the best solution to this deprecation.

```
[Warning] DEPRECATION: Accessing jQuery.Event specific properties is deprecated. Either use the ember-jquery-legacy addon to normalize events to native events, or explicitly opt into jQuery integration using @ember/optional-features. [deprecation id: ember-views.event-dispatcher.jquery-event] See https://emberjs.com/deprecations/v3.x#toc_jquery-event for more details. (vendor.js, line 12767)
    https://myapp.dev/assets/vendor.js:12855:25
    raiseOnDeprecation@https://myapp.dev/assets/vendor.js:12777:21
    https://myapp.dev/assets/vendor.js:12855:25
    invoke@https://myapp.dev/assets/vendor.js:12864:31
    deprecate@https://myapp.dev/assets/vendor.js:12836:34
    get@https://myapp.dev/assets/vendor.js:55342:107
    draggingOver@https://myapp.dev/assets/vendor.js:83481:62
    dragOver@https://myapp.dev/assets/vendor.js:83093:49
    superWrapper@https://myapp.dev/assets/vendor.js:53391:33
    _run@https://myapp.dev/assets/vendor.js:28050:40
    https://myapp.dev/assets/vendor.js:55215:38
    dispatch@https://myapp.dev/assets/vendor.js:5524:32
```

**Comment by dgavey** [comment]
Just released a version 0.5.1, try that out.  If you are still having issues, let me know what version your ember is and I'll take a look.

**Comment by boris-petrov** [comment]
@dgavey - thanks for taking the time for all the changes and fixes! We appreciate that!

As for this issue I suggest you wait until [this](https://github.com/emberjs/ember.js/issues/16849) is fixed in Ember/ember-optional-features as there is a problem in those two. It also might resolve this issue here.

**Comment by dgavey** [comment]
I think this should no longer be an issue as of 0.6.0
