### ISSUE TITLE
Drag doesn't work in Chrome on desktop in mobile mode

### ISSUE THREAD

**Issue by dantistus** [mharris717/ember-drag-drop#135]
The component doesn't work when opened in Chrome on desktop computer but in mobile mode:

![image](https://user-images.githubusercontent.com/1497083/44855494-73dad700-ac6b-11e8-9888-83935e597c3d.png)

**Comment by dgavey** [comment]
This addon isn't fully compatible with touch events.  Some people have used an additional addon with some success.  Check the readme for info on that.

**Comment by dantistus** [comment]
Thank you for a quick response. I have tried several addons among top-rated on https://www.emberaddons.com/ and this one worked best on actual mobile device for the task I have at hand...

**Comment by dgavey** [comment]
The mobile device must be mapping the touch events to simulate clicks and drags. That would explain why it's not working in mobile simulation mode on chrome.  I do hope to add first class touch support soon.

**Comment by dantistus** [comment]
Again, thank you very much for quick response. You are probably right. Other addons I have tried reacted to touch events directly and it seriously interfered with page scroll. With your addon, I have to press the draggable item for ~2 seconds for the drag action to start, but once it has started, it works very smoothly.
