### ISSUE TITLE
Bug when a sortable-objects component is destroyed

### ISSUE THREAD

**Issue by boris-petrov** [mharris717/ember-drag-drop#136]
There's actually two bugs:

1) When dragging a `draggable-object` inside a `sortable-objects` container, `dragStart` is called on both [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/draggable-object.js#L58) and [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/sortable-objects.js#L28). In `draggable-objects`'s implementation, `dragCoordinator.sortComponentController` is accessed [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/draggable-object.js#L79). It is set in `sortable-objects`'s `dragStart` [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/sortable-objects.js#L33). Which is *not* OK as `dragStart` on the `sortable-object` is called **after** the one on `draggable-object` (as that is how events work - first the immediate target and then bubbling). If what I'm saying is not clear, I can try rewording.

2) When a `sortable-objects` component is destroyed, it is not removed from `dragCoordinator.sortComponentController`. This means that the next drag event on a `draggable-object` will check an invalid `enableSort` and `dragCoordinator.sortComponentController` [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/draggable-object.js#L79). This perhaps could be fixed by adding a `this.set('dragCoordinator.sortComponentController', undefined);` in `sortable-object` `drop` [here](https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/sortable-objects.js#L49).

The first problem is probably difficult to fix and also it won't affect too many people so it's not that important. The second is a pretty major issue (with an easy fix). If you think that what I'm suggesting is OK, I could create a PR.

**Comment by dgavey** [comment]
For 2. I think that should fix the issue.  Go ahead and make a PR if you like.

**Comment by boris-petrov** [comment]
Here you go: https://github.com/mharris717/ember-drag-drop/pull/137

**Comment by dgavey** [comment]
Release in 0.6.0 thanks!
