### ISSUE TITLE
dragOverAction not firing

### ISSUE THREAD

**Issue by jcfinnerup** [mharris717/ember-drag-drop#138]
Hi there, 

I am experiencing that i cannot get dragOverAction to fire. 

Code:
```
    {{#draggable-object-target target="1" action=(action 'dragEndAction') amount=tab.order dragOverAction=(action 'overAction') }}
      {{#draggable-object content=tab  dragEndHook=(action 'outAction')}}
        <div class="tab-outer">
          <li class="nav-item tab">
            <span>
              <label>{{truncate tab.title 25}}</label>          
            </span>
          </li>
        </div>
      {{/draggable-object}}
    {{/draggable-object-target}}
```

the tab obj is defined in an outer #each 

```
    overAction(){
      console.log('Action Fired');
     }
```

The overAction is never fired, am i making a silly mistake?

**Comment by dgavey** [comment]
Your draggable-object is inside your target. In this use case scenario The draggable-target is in a different area than your draggable-object.

See Example.  http://mharris717.github.io/ember-drag-drop/#/simple Code is linked at the bottom of that page.

**Comment by jcfinnerup** [comment]
Thanks! I didn't know that would break it, i've moved it out and it works
