### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by Mithrilhall** [mharris717/ember-drag-drop#153]
Demo is not working.

**Comment by dgavey** [comment]
They all seem to be running from what I can see

**Comment by Mithrilhall** [comment]
[Demo link](https://mharris717.github.io/ember-drag-drop/horizontal)

**Comment by dgavey** [comment]
Try this -> http://mharris717.github.io/ember-drag-drop/#/horizontal

**Comment by Mithrilhall** [comment]
That works perfect. Thanks.

The links in the README are missing the #.

**Comment by dgavey** [comment]
Ah, great I'll update that, thanks.
