### ISSUE TITLE
Deprecation warning thrown when building project with ember-cli 

### ISSUE THREAD

**Issue by DanielOchoa** [mharris717/ember-drag-drop#16]
ember-cli version is 1.13.6
ember version is 1.13.7

DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper ('px-web-client/templates/components/object-bin.hbs' @ L5:C2) is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.

**Comment by dgavey** [comment]
I was on holidays last week, but I have a branch free of deprecations ready to be released. You should see a new release this week that fixes this and many other issues.

**Comment by dgavey** [comment]
Version 0.1.6 has been published and addresses this.
