### ISSUE TITLE
dragging "through" a draggable-object

### ISSUE THREAD

**Issue by GerritSommer** [mharris717/ember-drag-drop#160]
Hi, 
I am having the need to drag "through" a draggable object or hide the original dragged object.
I think it's best to visually show what I mean.
- I have hours, which are draggable-object-targets
- I have events which are draggable-objects
- I can drag an event to a free space in the target area
- I can not drag an event to a time which is covered by an event

In this case I CAN drag the event to another day, but I can not drag the event to 12:00, as that time is covered by the event

![drag-shifts](https://user-images.githubusercontent.com/3207218/58792854-44d80400-85f5-11e9-92d8-3e316d68ac0b.gif)

Is it possible to hide the original HTML element and only keep the dragged element?
I hope this is understandable.

PS: Awesome project

**Comment by GerritSommer** [comment]
Sorry, I found the solution myself via pointer-events.
I am using a drag handle and did set:
``
.drag-handle {
	pointer-events: auto;
}
.event.is-dragging-object {
	pointer-events: none;
}
``
This way the drag event is not captured by the draggable-object, but the drag-event is still handled by the drag-handle.

**Comment by dgavey** [comment]
Glad you found a solution and thanks for sharing it back here.
