### ISSUE TITLE
Possible to style sortable options like Spotify?

### ISSUE THREAD

**Issue by boonier** [mharris717/ember-drag-drop#177]
I'm trying to achieve this effect: 

![image](https://user-images.githubusercontent.com/6206789/94442055-68846d80-019b-11eb-82d8-fcbc249d27ca.png)

Where the index position indicator shows as a line, and the item being dragged shows as a tooltip.

Is something like this possible?

cheers

**Comment by dgavey** [comment]
Not really with the current events that are passed out. If you are using modern Ember (above 3.12) I would suggest just writing your components without this addon. 

I wrote about that here a while back -> https://dev.to/dgavey/simple-drag-and-drop-in-ember-octane-466i

**Comment by boonier** [comment]
Thanks for the quick reply.
