### ISSUE TITLE
Full Ember Octane Compatibility?

### ISSUE THREAD

**Issue by eric-g-97477** [mharris717/ember-drag-drop#204]
In the release notes for [Version 0.9.0-beta.0](https://github.com/mharris717/ember-drag-drop/releases/tag/v0.9.0-beta.0), it says:

> It would be difficult to get this project to a full Ember octane compatibility. The plan is to start a new more modern project for a Ember octane soon.

I am wondering what the status on this effort was...?

**Comment by dgavey** [comment]
I would not suggest using this with modern ember.  It uses old patterns.  It has not been updated to be Embrodier or fully octane compatible. I don't have a plan in place to do this.  My intention was to write something completely different, but the effort was never completed. The readme has a link to a blog post on how you could make it yourself using modern ember patterns.
