### ISSUE TITLE
Error thrown with draggable-object-target.

### ISSUE THREAD

**Issue by lcpriest** [mharris717/ember-drag-drop#27]
I'm having an issue with `{{#draggable-object-target action="dropEvent"}}`.
I can't recreate it in a fresh app, but I was wondering if you have seen this before and have any tips?

`Uncaught TypeError: Can't add property _currentDrag, object is not extensible droppable.js:159`

**Comment by dgavey** [comment]
Yes, this is an error with Ember 2.3.0 + I have a PR for it ready to go, I will pull it in tonight and release a new version to fix it.

**Comment by lcpriest** [comment]
Excellent, thanks for your help!
