### ISSUE TITLE
Sortable (beta)

### ISSUE THREAD

**Issue by lcpriest** [mharris717/ember-drag-drop#28]
I'm currently building a mildly more advanced version of the 'Classify Posts' example, you can sort them also. I'm running into the issue that the individual lists are not sorting internally.

I can drop a new item on any position of the list and it will place itself to the end of the list, but when it's just working with elements from it's own list, they are not switching positions before firing the sortEnd action.

`template.hbs`
```
{{#draggable-object-target action="dropEvent"}}
  {{#sortable-objects sortableObjectList=sortableObjectList sortEndAction='sortEnd' enableSort=true}}
    {{#each sortableObjectList as |card|}}
      {{#draggable-object content=card isSortable=true}}
        <div class="card-item">
          <h2>{{card.title}}</h2>
        </div>
      {{/draggable-object}}
    {{else}}
      <div class="dropzone"></div>
    {{/each}}
  {{/sortable-objects}}
{{/draggable-object-target}}
```

`component.hbs`
```
import Ember from 'ember';

export default Ember.Component.extend({

  actions: {
    dropEvent(content) {
      if (this.get('unsorted')) {
        content.set('section', undefined);
        content.set('sectionOrder', 0);
      } else {
        content.set('section', this.get('section'));
      }
      content.save();
    },

    sortEnd(content) {
      if (!this.get('unsorted')) {
        debugger
      };
    },
  },
});
```

Is there anything glaring I am missing? sortableObjectList is an unsorted array of card objects.

**Comment by dgavey** [comment]
I think the issue here is I've never tried an area that is both a target and a sort area at the same time.  Both components tap into the dragEnd event. It's highly likely one is overriding the other.  I'll have to put together an example to see if I can get it working.

**Comment by lcpriest** [comment]
Actually, I'll do a bit more research and get back to you, it is looking like it might be an issue on my end.

**Comment by lcpriest** [comment]
With the classify posts example, is there any reason that you can see that you couldn't also **Unclassify** posts?

I think that is my issue here. My implementation has multiple drop zones,

- Unclassified posts (unsorted)
- Class 1 sorted
- Class 2 sorted

That template and component above are encapsulated as a `{{cards-list}}`.
```
      {{#each board.sections as |section|}}
        {{cards-list cards=section.cards section=section}}
      {{/each}}
      {{cards-list cards=board.cards unsorted=true}}
```
