### ISSUE TITLE
DragCoordinator

### ISSUE THREAD

**Issue by lcpriest** [mharris717/ember-drag-drop#29]
Follow up from https://github.com/mharris717/ember-drag-drop/issues/28

https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/sortable-objects.js#L14

This line looks like it is impossible to have more than one sortableList per page.

**Comment by dgavey** [comment]
Yes, that's correct, I can do a small refactor to change that though, we should be able to set that on the dragStart and unset it on dragEnd instead.

**Comment by lcpriest** [comment]
Awesome!

**Comment by dgavey** [comment]
Gonna leave this open as a reminder for me to do that.

**Comment by dgavey** [comment]
I've added the simple refactor on release 0.33 to allow multiple sort containers on the same page. There is a larger refactor coming that will allow nested multiple sorted items.  One bug in the currently release is you can drag an item from one list to the other right now.  That will be addressed with the bigger refactor.  If it's an issue right now, you should be able to work around it by disabling the one sort container while the other is being sorted.
