### ISSUE TITLE
Dragging container with draggable object throws error

### ISSUE THREAD

**Issue by jacojoubert** [mharris717/ember-drag-drop#31]
If you click and drag on the containing div a javascript error is thrown. 

`drag-coordinator.js:53 Uncaught TypeError: Cannot read property 'target' of null`

Easily replicated on the demos. Just click and drag on the white space between the boxes: http://mharris717.github.io/ember-drag-drop/sort

**Comment by dgavey** [comment]
Thanks for the bug report, should be a pretty easy bug to address.

**Comment by dgavey** [comment]
Fixed in release 0.3.3
