### ISSUE TITLE
Using dragHandle raises ember-views.dispatching-modify-property deprecation

### ISSUE THREAD

**Issue by remkoboschker** [mharris717/ember-drag-drop#36]
I'm on 2.5.1

Also with many objects (30 +) on page you start to notice the performance issues. 

On a side note drag and drop is working well with 10 sortable target areas (without the dragHandle).

I'll attempt a fix.

Thank you

**Comment by remkoboschker** [comment]
In draggable-object.js 
````
  didInsertElement: function() {
    let self = this;
    //if there is a drag handle watch the mouse up and down events to trigger if drag is allowed
    if (this.get('dragHandle')) {
      //only start when drag handle is activated
      if (this.$(this.get('dragHandle'))) {
        //this.set('dragReady', false);
        this.$(this.get('dragHandle')).on('mouseover', function(){
          self.set('dragReady', true);
        });
        this.$(this.get('dragHandle')).on('mouseout', function(){
          self.set('dragReady', false);
        });
      }
    }
````
not setting the `dragReady` to false fixes the issue. I'm not sure if this introduces any other issues. I assume you did not put it there for nothing. @mharris717 @dgavey Could you please advise?

I can check if the `dragHandle` property is set on the component and initialise the `dragReady` to false at component initialisation. Would that solve any other issues?

Happy to prepare a pull request.

**Comment by dgavey** [comment]
Your solution should work ok.  I'm still a bit baffled why that was causing so many performance issues.  Other than it's known that setting visual changes in didInsertElement can cause performance issues. 

If you could prepare a PR that would be awesome.  Thanks for checking on the tests as well.

**Comment by remkoboschker** [comment]
Thank you for the quick response. I have made a pull request #37. I'm not sure why the page was stalling with just this simple redraw. Each time I clicked a handle the warning was raised 72 times.
