### ISSUE TITLE
Re ordering algorithm behaves strangely

### ISSUE THREAD

**Issue by juanazam** [mharris717/ember-drag-drop#48]
Hi,
First of all, thanks for this addon, it's great! I ran into a small issue while using it:

Given a horizontal list: [A, B, C, D, E]

With the current swap logic, if I try to drag D to A (without dragging the element over the list) we will get: [D, B, C, D, E], which doesn't seem to be the intuitive result. I would expect the result list for this case to be [D, A, B, C, D, E].

This happens because of the current `swapObjectPositions` method implementation on the service.

Wouldn't it make sense to change that? If you think so I can create PR with code that changes that behavior.

```js
  swapObjectPositions: function(a, b) {
      var newList = this.get('arrayList').toArray();

      var newArray = Ember.A();
      var aPos = newList.indexOf(a);
      var bPos = newList.indexOf(b);
      newList.splice(aPos, 1);
      newList.splice(bPos, 0, a);

      newList.forEach(function(item){
        newArray.push(item);
      });

      this.set('sortComponentController.sortableObjectList', newArray);
  }
```

Hope I made myself clear.

Cheers!

**Comment by dgavey** [comment]
Hey, unfortunately the addon doesn't currently work with horizontal lists.  I had a PR before to fix it, but it broke vertical lists.  I'd love to have a PR on it, but we will have to have a test, and the solution needs to work for both vertical and horizontal lists, or at least have a flag so the user can choose what kind of sorting to do.  Another condition is that it most not break the ability on a vertical list to drag outside of the list and then back in without and still only swap the node it hovers over.

**Comment by dgavey** [comment]
Let me know if you can do a PR with a test, if not, it's high on my list of things to do for this addon.

**Comment by juanazam** [comment]
@dgavey I could reproduce this issue with the vertical list on the demo site (I used the ember data example). You just need to drag box 1 to box 3 without draggin over box 2. Anyway, I was using the addon as it horizontally and it was behaving as expected except for this issue (that also happens vertically). Anyway I can to create tests for the horizontal case.

**Comment by dgavey** [comment]
Yes, that's not a bug in the vertical list, it's a feature.  In a vertical list someone should be able to drag outside the list and swap with the other item.  At least our use case for this benefits from it.  It doesn't make sense for horizontal lists though.  Which is why perhaps we should have the alternate sort behind a flag.

**Comment by juanazam** [comment]
Ok, got it, I agree that having a flag makes sense, but I'm not sure if vertical or horizontal flag is what we are looking for. I think we could make ir more general, we can let the user configure the swapping mechanism, so we would support  the 'swap' mechanism and this other mechanism. I think this way is a bit better because someone might want to use any of these mechanism regardless of the list being vertical or horizontal.

Does this make sense?

**Comment by dgavey** [comment]
Yeah for sure, I think maybe something like allowSwap true/false. default to true (for backward compatibility)

**Comment by juanazam** [comment]
@dgavey makes sense, I will try to work on this soon and open a PR, thanks
