### ISSUE TITLE
Shifting items with different sizes in a `sortable-objects` components has an issue.

### ISSUE THREAD

**Issue by joankaradimov** [mharris717/ember-drag-drop#53]
It appears that the if the `draggable-object` components inside a `sortable-objects` have differing sizes, that can lead to some issues. I have been able to reproduce it with shifting. I don't know if the issue exists when swapping.

I am able to reproduce this on the demo page with a bit of tweaking. The steps are as follows:
* Go to the [sortdata example](http://mharris717.github.io/ember-drag-drop/#/sortdata)
* Open the browser's development tools and manually set some height (e.g. 200px) for a certain element (e.g. "Page Title 2")
* Pick some other element (e.g. "Page Title 4") and start moving it around. Move it above the larger element and then - below the larger element.
* I consistently end up with an ordering that shouldn't be possible if only one element has been moved (e.g. The ordering ends up being `1, 3, 2, 4` after having touched only element `4`)

I don't know if the examples are up to date, but in the project I am working on I observe the same behavior using ember-drag-drop 0.3.7.

**Comment by dgavey** [comment]
Have you tried on the new demo?  http://mharris717.github.io/ember-drag-drop/#/horizontal  That one enables a shifting as opposed to the swapping algorithm.  Maybe that would work better for you?

**Comment by joankaradimov** [comment]
Sorry, I was mislead by the naming of the parameter. I assumed that omitting `useSwap` is the same as using `useSwap=false`.

**Comment by dgavey** [comment]
That is a bit confusing, sorry about that. Was trying to keep backward compatibility so useSwap defaults to true.
