### ISSUE TITLE
Issue when dragging between different sortable-objects components

### ISSUE THREAD

**Issue by joankaradimov** [mharris717/ember-drag-drop#54]
If you go to the [example with two sortable-objects components](http://mharris717.github.io/ember-drag-drop/#/sort) and try to drag from one `sortable-objects` component to the other, the dragged item from the first replaces the draggable item for the other component. If you keep doing this strange things start happening with the text in the boxes.

I assume that the expected behaviour would be to disallow dragging items from from one `sortable-objects` component to another.

**Comment by joankaradimov** [comment]
Sorry, just now I saw that this is a duplicate of https://github.com/mharris717/ember-drag-drop/issues/51

**Comment by dgavey** [comment]
I do have a fix incoming that will make sorting multiple lists much easier, been trying to find time to fix the merge issues I have with it. Hopefully soon.
