### ISSUE TITLE
Deprecation warning and object error in console (Ember 2.7) - dropping a file object

### ISSUE THREAD

**Issue by rmcsharry** [mharris717/ember-drag-drop#62]
Can this be used to drop a file from outside the browser window as the dropped object?

When I try to do that, I see these errors in the console:

DEPRECATION: The `length` property of `<(unknown mixin):ember442>` is an `Ember.Binding` connected to `contentLength`, but `Ember.Binding` is deprecated. Consider using an `alias` computed property instead. [deprecation id: ember-metal.binding] 
See http://emberjs.com/deprecations/v2.x#toc_ember-binding for more details.

trekclient.js:451 Uncaught no obj for key getObj @ trekclient.js:451getObject @ trekclient.js:400handlePayload @ vendor.js:87221handleDrop @ vendor.js:87228acceptDrop @ 

451 Uncaught no obj for key

**Comment by dgavey** [comment]
Unfortunately this addon is only intended to allow internal dragging and dropping.  Give [Dropzone](https://www.npmjs.com/package/ember-cli-dropzonejs) a try.
