### ISSUE TITLE
Dropping an object on a target causes redirect in Firefox

### ISSUE THREAD

**Issue by johanobergman** [mharris717/ember-drag-drop#7]
When you drag and drop a draggable object into a target using Firefox (I'm using 35.0), the browser redirects to a url consisting of several seemingly random digits. This only happens in Firefox.

**Comment by dgavey** [comment]
I just fixed this, I am submitting a pull request for it.

**Comment by tzumainn** [comment]
Was a fix for this issue able to be merged?  Thanks!

**Comment by dgavey** [comment]
This has been merged and is part of 0.1.5
