### ISSUE TITLE
`useSwap` option not working

### ISSUE THREAD

**Issue by patrickberkeley** [mharris717/ember-drag-drop#73]
Unless I completely misunderstand what swap is supposed to do,`useSwap=true` doesn't change anything. I see the default is `true` but regardless, items in a list are always shifted, not swapped.

See the demo: http://mharris717.github.io/ember-drag-drop/#/horizontal

**Comment by dgavey** [comment]
You're right, it looks like something broke along the way, I know I have a test for this too.  Hmm I'll look into it.

**Comment by dgavey** [comment]
The demo does seem to be not work, but the test is passing.  And I enabled it on a production app and it worked as expected.  Still not sure why the demo is failing.

**Comment by patrickberkeley** [comment]
Huh, strange. It definitely doesn't seem to be doing anything in our app running locally.

**Comment by dgavey** [comment]
I just realized we are still using 0.37 version of this addon on production.  So I'd say it probably broke after that.

**Comment by dgavey** [comment]
Pushed up a fix for this, it was the result of a bad merge.  Will go out with the next release.

**Comment by patrickberkeley** [comment]
Great! Thank you @dgavey .

**Comment by dgavey** [comment]
Published on v0.4.2

**Comment by JoshSmith** [comment]
Thanks for the report @patrickberkeley.
