### ISSUE TITLE
The log helper is breaking Ember 2.10

### ISSUE THREAD

**Issue by boris-petrov** [mharris717/ember-drag-drop#77]
Check this issue in Ember.js's repo:

https://github.com/emberjs/ember.js/issues/14653

Please remove it ASAP for Ember 2.10 compatibility.

**Comment by rwjblue** [comment]
https://github.com/mharris717/ember-drag-drop/pull/78 should fix

**Comment by dgavey** [comment]
I had no idea that was even in there.  Must of been some very old legacy code.  I'll work on this tonight and get it released.  I need to upgrade to 2.10 and get all my tests passing again as well.  Thanks for the PR.

**Comment by dgavey** [comment]
Fixed with release 0.4.1 :-)
