### ISSUE TITLE
HTML data not rendered in sortableObjectList

### ISSUE THREAD

**Issue by chrishandy9** [mharris717/ember-drag-drop#82]
Hello,

I'm trying to populate the sortableObjectList array dynamically and have its contents be sortable. Any HTML  that's set in the array doesn't get rendered in the handlebars, is there a reason for it?

**Comment by dgavey** [comment]
Not that I'm aware, but I'd need to see an example of what you're trying to do to know for sure. Either in an ember-twiddle or more info here.

**Comment by chrishandy9** [comment]
OK I'll do my best to explain it here, I'm unable to write a twiddle at the moment.

I have a select list item that on change, calls an action:
`sortableFieldList = [];`


```
selectFormType(fieldType) {            
     let field = this.formField(fieldType.value);
     this.sortableFieldList.push( {title: field});
      this.set('addField', true);
 }
```

formField is the function that generates the html that I push to the array:

```
formField(type){
        let table = document.createElement('table'),
            remove_field = document.createElement('a'),
            row_html;

        this.set('addField', false);

        switch (type){
            case 'text':
                row_html = '<tr><th>Text field</th><th><a class="remove_field"> removie field</a></th></tr><tr><td>Field Name:</td><td><input type="text"/></td></tr><tr><td>Field Placeholder:</td><td><input type="text"/></td></tr>';
                break;
            case 'select':
                row_html = '<tr><th>Select field</th><th><a class="remove_field"> removie field</a></th></tr><tr><td>Field Name:</td><td><input type="text"/></td></tr><tr><td>List contents:</td><td><textarea></textarea></td></tr>';
                break;
            case 'radio':
                row_html = '<tr><th>Radio field</th><th><a class="remove_field"> removie field</a></th></tr><tr><td>Field Name:</td><td><input type="text"/></td></tr><tr><td></td></tr>';
                break;
            default:
                row_html = 'default - something went wrong';
                break;
        }
       /* $('.remove_field').on('click', function(){
            console.log($(this).parents('table'));
            $(this).parents('table').remove();
        });*/

        //table.innerHTML = row_html;
        $(table).append('<div style="background-color:blue;width: 100px;height: 100px;">adfdgfojdfgoisdjfgosd</div>');

        return table;
}
```

"addField" is a property that's listened on if it changes, which is a computed function:

```
fieldListArray: computed('addField', 'sortField', function(){
        let fieldAdded = this.get('addField');

        console.log(fieldAdded);
        if (!fieldAdded) {
            return 0;
        }

        return Ember.A(this.sortableFieldList);
})
```


in my hbs, 


```
{{#sortable-objects sortableObjectList=fieldListArray sortEndAction='sortEndAction' enableSort=true}}
	{{#each fieldListArray as |item|}}
		{{#draggable-object content=item overrideClass='sortObject' isSortable=true dragEndAction='dragEndAction'}}
			inside draggable {{item.title}}
		{{/draggable-object}}
	{{/each}}
{{/sortable-objects}}
--------------------------------------------------------------------
{{#each fieldListArray as |item|}}
	{{item.title}}
{{/each}}
```


The foreach below the break renders the html fine, but in the sortable-objects array, they aren't rendered.

If you need more information please let me know

**Comment by chrishandy9** [comment]
For some reason everything works now, not sure what I did to fix it but I'll close this and re-open if it becomes an issue again

**Comment by dgavey** [comment]
Sorry got busy there. What your doing in the switch statement is very un-ember like.  I'm sure there is a way to refactor it so that your HTML is not in the JS code but in the HBS.  Also using createElement directly is very unusual and can cause a lot of problems with the Glimmer engine. Glimmer needs to know when elements are created an destroyed in order to be efficient and this will definitely cause problems.

**Comment by chrishandy9** [comment]
No worries. I'm pretty new to Ember so I'm not necessarily familiar with the 'ember-like' ways of making things work. I'm not going to ask you to re-write my code but could you shed some light or point me in the direction of how it should properly be structured?

**Comment by dgavey** [comment]
Just some general notes for you.  In Ember you should never have to create any HTML in the JS.  You should use the handlebars templates for that.  In a table row your going to want to use the {{#each}} to generate those table rows.  Inside the Each use an If to manipulate the rows as necessary.  Hopefully that helps.  The ember docs are pretty decent and should help you out I hope.
