### ISSUE TITLE
`log` helper breaks console log statements in `hbs` templates

### ISSUE THREAD

**Issue by mmanwill** [mharris717/ember-drag-drop#83]
When trying to log out data in the console (e.g. `{{log 'asdf'}}`), the following error message appears:

> "Assertion Failed: You attempted to overwrite the built-in helper "log" which is not allowed. Please rename the helper."

A little digging seems to point to ember-drag-drop as the author of the conflicting helper. I'm on Ember 2.10.2

**Comment by dgavey** [comment]
This was fixed in late November, Release 0.42 should have the fix I believe.

**Comment by mmanwill** [comment]
You are correct. Indeed it was fixed.
