### ISSUE TITLE
Sortables draggable, but not droppable

### ISSUE THREAD

**Issue by toreric** [mharris717/ember-drag-drop#86]
Hey, emberizas! I have installed `ember install ember-drag-drop`.  I use `ember-cli 2.10.0` on Ubuntu 14.04.5. The project is built, and run with an Express server (`node server.js`), and the file name list (`allNames`) comes from Nodejs reading a disk directory. Now: I have great expectations regarding this ember-drag-drop! However:

I did set up this template code in order to display a set of thumbnails as a sortableObjectList in order to make it possible to sort their order like in http://mharris717.github.io/ember-drag-drop/#/horizontal :
```hbs
...
{{#sortable-objects sortableObjectList=allNames sortEndAction='sortEndAction' enableSort=true useSwap=false}}
  {{#each allNames as |file|}}
    {{#draggable-object content=this isSortable=true overrideClass='show-inline'}}
    <div id="i{{file.name}}" class="img_mini">
      <div {{action 'showShow' file.show file.name}}>
        <img src="{{file.mini}}" title="{{file.orig}}" draggable="false">
      </div>
      <div class="img_name">
        {{file.name}}
      </div>
    </div>
    {{/draggable-object}}
  {{else}}
    T H I S &nbsp; I S &nbsp; E M P T Y
  {{/each}}
{{/sortable-objects}}
...
```
The introduction of the above drag-drop helpers did not change the appearance of the rendered page (that is, still looks nicely untouched). Now each img_mini block is draggable, including its img and img_name. The resulting generated html is (Firefox evaluation):
```js
...
<div id="ember366" class="sortable-objects ember-view">
  <div draggable="true" id="ember402" class="js-draggableObject show-inline ember-view">
    <div id="i2009-08-slaget" class="img_mini">
      <div data-ember-action="" data-ember-action-403="403">
        <img src="imdb/_mini_2009-08-slaget.png" title="imdb/2009-08-slaget.jpg" draggable="false">
      </div>
      <div class="img_name">
        2009-08-slaget
      </div>
    </div>
  </div>
  <div draggable="true" id="ember405" class="js-draggableObject show-inline ember-view"> ... </div>
  <div draggable="true" id="ember408" class="js-draggableObject show-inline ember-view"> ... </div>
  ... etc. until 29 js-draggableObject s
</div>
...
```
Did I position those handlebars as intended? The draggable blocks are not droppable, and my browser console prints `TypeError: aSortable is undefined`. Also, compared to the "horizontal" example, the class  `sortObject` is missing along `js-draggableObject` ... etc. However, by introducing `overrideClass='sortObject show-inline'` I succeded to generate the equal html, but the droppability still didn't appear ("rubber-band-return"), and the aSorttable error remained.

P.S. Think I found where the  aSortable error is generated:
```
   Next to line 79 in  the file
     node_modules/ember-drag-drop/addon/drag-coordinator.js
   I added a console.log line:
   ...
 79 moveObjectPositions(a, b, sortComponents) {
    console.log (sortComponents); // <<<<< inserted
      const aSortable = sortComponents.find((component) => {
        return component.get('sortableObjectList').find((sortable) => {
          return sortable === a;
   ...
   It prints sortComponents as
   Array [ Object ]

   When instead only the first element sortComponents[0] is referenced,
   ...
 79 moveObjectPositions(a, b, sortComponents) {
    console.log (sortComponents[0]); // <<<<< inserted
    etc ...

   it prints
   Object { __ember1488451093353: "ember377", __ARGS__ [id=__ember14884510933531313301298902]: Object, sortableObjectList: Array[29], sortEndAction: "sortEndAction", enableSort: true, useSwap: false, overrideClass: "show-inline", attrs: Object, parentView: Object, __HAS_BLOCK__ [id=__ember1488451093353140035755179]: true, 13 more… }

   Next after this line, the console prints
   TypeError: aSortable is undefined

   which, apparently, is generated when aSortable is referenced at line 97,
   const newList = aSortable.get('sortableObjectList').toArray();
   (in the built version, const is replaced by var, what's the reason?)
```

**Comment by dgavey** [comment]
One thing I see off the top, is that `content=this` should say `content=file`

**Comment by toreric** [comment]
Thanks! How can such things happen? And the `sortObject` class is obsolete ... If no more comments I'll close this tomorrow. Thank you, proceeding!!!
