### ISSUE TITLE
Writing acceptance and integration tests

### ISSUE THREAD

**Issue by Azdaroth** [mharris717/ember-drag-drop#91]
Hi! Thanks for this awesome addon. 

I was wondering how would you suggest writing integration and acceptance tests for the features where dragging & dropping is involved? I guess it would be doable by breaking the interaction into triggering single events at the proper moment, but this is not that simple. Do you have any recommendations how to do it efficiently?

**Comment by dgavey** [comment]
Triggering events is the only way right now, I do have a PR I need to merge that brings in a helper for that, but it's not quite ready yet.

**Comment by robustdj** [comment]
This is the [PR](https://github.com/mharris717/ember-drag-drop/pull/76). @dgavey let me know it needs in order for it to be ready. Thanks!

**Comment by dgavey** [comment]
I plan on bringing them in soon, expect a release in the next week, sorry for the delay.

**Comment by QuantumInformation** [comment]
I'm about to support drag and drop in my [test recorder](https://github.com/QuantumInformation/test-recorder). Not sure whether to use your helpers or just generate the code to trigger events (which might bloat too much).

**Comment by dgavey** [comment]
The helpers were released you should be able to use them, instructions are in the readme
