### ISSUE TITLE
property to disable draggable target

### ISSUE THREAD

**Issue by ksnyde** [mharris717/ember-drag-drop#93]
I have draggable targets which depend on state to determine whether they should be treatable as activated or not. Is there a property that one can set to provide this functionality?

**Comment by dgavey** [comment]
Sure do, in the {{draggable-object}} pass in isDraggable=false.  That should work for ya.

**Comment by ksnyde** [comment]
great! many thanks.

**Comment by ksnyde** [comment]
Finally got around to implementing this and realised that this backwards from what I need. The state that is dynamic is not contained in the _draggable-object_ but rather the _draggable-target_. 

In my case I have a calendar and certain days can dynamically become a holiday or full-subscribed. In both cases that target should no longer accept droppables.

**Comment by ksnyde** [comment]
Guess I can't reopen this. Will open another issue instead.
