### ISSUE TITLE
Component broken when nest draggable-object

### ISSUE THREAD

**Issue by biblesyme** [mharris717/ember-drag-drop#99]
If I use it like below
```
{{#sortable-objects useSwap=true sortableObjectList=model sortEndAction='sortEndAction' enableSort=true sortingScope="sortingGroup"}}
      {{#each model as |item|}}
        {{#draggable-object isDraggable=false dragHandle='.js-dragHandle' class="steps-wrap" content=item overrideClass='sortObject' isSortable=true sortingScope="sortingGroup"}}
                 {{#sortable-objects class=sortingScope sortableObjectList=model 
                       sortEndAction='sortEndAction' enableSort=true sortingScope=sortingScope}}
                       {{#each model as |item|}}
                           {{#draggable-object class="step-content {{stageId}}" content=item overrideClass='sortObject' isSortable=true sortingScope=sortingScope}}
                               <div class="step-name text-muted">test step{{item.id}}</div>
                           {{/draggable-object}}
                      {{/each}}
              {{/sortable-objects}}
        {{/draggable-object}}
      {{/each}}
    {{/sortable-objects}}

```

**Comment by dgavey** [comment]
They haven't been tested nested.  I don't think that would work.  However if you have two sortable objects on the same template. You must pass a unique sortingScope name to each.  In the nested one you are using sortingScope=sortingScope and I'm not sure if it's defined.

**Comment by biblesyme** [comment]
yes, the `sortingScope` is defined it. when I use it out of the parent draggable-objects, it works fine. But, once I nest it. It's broken. So, I don't how to fix this.

**Comment by dgavey** [comment]
The way the addon is currently created, having a nested {{sortable-objects}} won't work.  Without writing a bunch of changes to support this I don't currently have a workaround for you.

**Comment by biblesyme** [comment]
Ok,thanks,  Maybe I have to try another addon to help me achieve this. 
I wanna know if this feature is doable?

**Comment by n1ru4l** [comment]
@biblesyme Do you have any success with other addons?
@dgavey Do you plan to support this in the future?
